### ISSUE TITLE
Index pages and tags renaming

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#10]
If a tag is renamed, index pages are not regenerated

Add content.tags to the Etag

class ListingContentGenerator(ContentGenerator):
 @classmethod
    def get_etag(cls, post):
        return hashlib.sha1((post.title + post.summary + str(post.tags)).encode('utf-8')).hexdigest()

**Comment by Arachnid** [comment]
Duplicate of issue 7.
