### ISSUE TITLE
Only the tag path should be slugified

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#15]
After the last commit, the tag and its path are slugified.
Only the path should be slugified.

Example : my tag = "Héllo", the path should be /tag/hello but "Héllo" must always be displayed.
i.e: <a href="tag/hello">Héllo</a> and not <a href="tag/hello">hello</a>

**Comment by Arachnid** [comment]
Fix tag escaping. Closed by 79878dc87fac43d45a614966f35552b3f09d7ef7
