### ISSUE TITLE
VersionInfo and cse, search are not created after a datastore clear

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#16]
If I delete everything without uploading a new version, then VersionInfo, cse, search will not be recreated. First we have to upload a new version.

CURRENT_VERSION_ID is not changed, so it will raised an error.

def run_deploy_task():
    """Attempts to run the per-version deploy task."""
    task_name = 'deploy-%s' % os.environ['CURRENT_VERSION_ID'].replace('.', '-')
    try:
        deferred.defer(try_post_deploy, _name=task_name, _countdown=10)
    except (taskqueue.TaskAlreadyExistsError, taskqueue.TombstonedTaskError), e:
        pass

**Comment by Arachnid** [comment]
Not really a bug - if you erase the datastore, there'll be all sorts of issues. The forthcoming regeneration support may help with this, though. In the meantime, you can run post_deploy() manually using remote_api.

When you say "it will raised an error" - do you actually get an error?

**Comment by sylvainvivien** [comment]
Sure it's not really a bug. When I said it raised an error, it is just it enter the "except":pass. It was more a remark than a bug and/or to add this in the doc. (i.e. : if you erase the db then you have to rebuild or upload a new version)

**Comment by Arachnid** [comment]
Static templates are now regenerated using the 'regenerate all' support.
