### ISSUE TITLE
Tab label on "Edit a post"

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#17]
If I edit a post, the tabs (HOME / POSTS / NEW POST) should be (HOME / POSTS / EDIT POST)
- change "NEW POST" -> "EDIT POST"

**Comment by Arachnid** [comment]
Er? But the 'new post' link is for new posts, not editing posts.

**Comment by sylvainvivien** [comment]
If you go there .../admin/ then select a post.
The title is "Edit post" but the tab is "New post". IMO, I don't think it's very logical.
It should be "Edit post" everywhere.

Here is a screen : http://nopix.appspot.com/o/ysLlBfDVxT85Y0KGxhANjbzWL.jpg

**Comment by Arachnid** [comment]
Fixed.
