### ISSUE TITLE
Wrong post counts on admin page

### ISSUE THREAD

**Issue by andialbrecht** [Arachnid/bloggart#19]
Post counts on the admin page are off by one. Here's a patch to fix it: http://gist.github.com/214940

Note, this patch adds a new column with two actions (view, edit) to the list of posts table too. I've found this very handy :)

**Comment by Arachnid** [comment]
Thanks for this! Applying it now.

**Comment by andialbrecht** [comment]
Here's an update: http://gist.github.com/217089

The draft option didn't exist when I posted the patch :)

**Comment by Arachnid** [comment]
Applied - thanks!
