### ISSUE TITLE
Better 404 handling

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#20]
Currently 404 results in a blank page.

We can add a custom Google 404 ?

<script type="text/javascript">
  var GOOG_FIXURL_LANG = 'en';
  var GOOG_FIXURL_SITE = 'http://www.example.com'
</script>

<script type="text/javascript"
  src="http://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js">
</script>

http://www.google.com/support/webmasters/bin/answer.py?answer=136085

**Comment by Arachnid** [comment]
Yes, a proper 404 page is definitely a todo - thanks for filing the issue. :)

I'm not 100% certain how to handle it in the static code - possibly it should attempt to load and serve a special path for error pages, and serve up a generic oneliner if it can't find it. The Google 404 gadget would be an interesting addition, too.

**Comment by ghost** [comment]
this issue seems to be fixed in git, should this be closed ?

**Comment by Arachnid** [comment]
Good point!
