### ISSUE TITLE
Set bug : def _regenerate_sitemap():

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#26]
I've finished to update bloggartornado with the last changes but I've an error here :

set('/sitemap.xml', rendered, 'application/xml', False)
TypeError: set expected at most 1 arguments, got 4

To fix my version : import static and static.set
Maybe you have the same issue ?

def _regenerate_sitemap():
    import static
    paths = _get_all_paths()
    rendered = render_template('sitemap.xml', {'paths': paths})
    static.set('/sitemap.xml', rendered, 'application/xml', False)

**Comment by sylvainvivien** [comment]
Another thing, if there is an error with the set 'keyword' (i.e. : set / frozenset), maybe the set function in static should be renamed : set_static or something like that.

**Comment by Arachnid** [comment]
Quite right - thanks. The name shouldn't be too much of a problem because it's almost universally called from outside the static module, where it's fully qualified.

**Comment by Arachnid** [comment]
Fixed missing import. Closed by d920aa8eb53d1904c1386325af9c801772519112.
