### ISSUE TITLE
Add ping feature

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#27]
When a new post is added, it could be nice to "ping" many services. (like pubsubhub I think):
- blogsearch : http://www.google.com/help/blogsearch/pinging_API.html#rest
- friendfeed : http://friendfeed.com/api/public-sup
- feedburner : http://www.feedburner.com/fb/a/pingSubmit
- google sitemap ping : http://www.google.com/support/webmasters/bin/answer.py?hl=fr&answer=34609
- etc,... :)

**Comment by Arachnid** [comment]
I think most of these are a dead-end - hubbub is likely to replace them in the near future. The sitemap ping might be worth implementing, though.

**Comment by ghost** [comment]
patch for this  http://github.com/bholtsclaw/bloggart/commit/09b04cf40d76c9aa91ce52a6ab1d7286cc59eb48

**Comment by Arachnid** [comment]
Fixed by bholtsclaw.
