### ISSUE TITLE
Support compress sitemap

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#29]
Support compress sitemap .xml.gz,....

**Comment by ghost** [comment]
here is a commit to fix this issue

http://github.com/hickups/bloggart/commit/559c10e77fad9ac82ca972788f7146764561fbf5

**Comment by Arachnid** [comment]
Fixed by hickups.

**Comment by sylvainvivien** [comment]
I think the robots.txt should be updated too.
http://github.com/Arachnid/bloggart/blob/master/themes/default/robots.txt

Sitemap: http://{{config.host}}{{config.url_prefix}}/sitemap.xml.gz
