### ISSUE TITLE
Draft posts not excluded from Atom feeds

### ISSUE THREAD

**Issue by andialbrecht** [Arachnid/bloggart#30]
This morning two new posts showed up in my Google Reader. "Efficient model memcaching" with complete text and correct URL. And "Blogging on App Engine, part 10: Review" without content and an invalid URL pointing to http://blog.notdot.netnone/

**Comment by sylvainvivien** [comment]
I think, I've the same issue with Bloggartornado if a Published date is set to None. In my case, it crashes.

**Comment by ghost** [comment]
went to fix this in the code and it seems to have been fixed already, should this issues be closed ?

**Comment by Arachnid** [comment]
Fixed.
