### ISSUE TITLE
Atom, islice error

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#32]
django does silent failure (bad I think or it should be disabled), tornado not so it's easier to check error.

So, I think there is an error here in your atom feed : 
<updated>{{posts.0.updated|date:"Y-m-d\TH:i:s\Z"}}</updated>

because : posts = itertools.islice((x for x in q if x.path), 10)
and posts[0] will fail
TypeError: 'itertools.islice' object is unsubscriptable

It's blank in blog.notdot.net : <updated></updated>

**Comment by sylvainvivien** [comment]
I've patched my version this way, certainly not the best... anyway...

# Fetch the 10 most recently updated non-draft posts

posts = itertools.islice((x for x in q if x.path), 10)
posts = [p for p in posts]

**Comment by Arachnid** [comment]
Turn the iterator into a slice for atom content generation. Closed by f4e3aab6272ff4b2ae8d19659198d7ebe1c5e25b.

**Comment by Arachnid** [comment]
Fixed, thanks. A neater solution is to just wrap the islice call in a list() call.
