### ISSUE TITLE
"No module named markdown"

### ISSUE THREAD

**Issue by hymerman** [Arachnid/bloggart#33]
git clone git://github.com/Arachnid/bloggart.git
git submodule init
git submodule update

"Run" using Google AppEngine Launcher
Visit http://localhost:8080, see 404 error
Visit http://localhost:8080/admin/, see stack trace for an exception thrown in the 'import markdown' line in markup.py:

<type 'exceptions.ImportError'>: No module named markdown
      args = ('No module named markdown',)
      message = 'No module named markdown' 

I've installed Python 2.5.4 from python.org and AppEngine is using this. I've done nothing else, and made no modifications to bloggart. I couldn't see any other instructions so I assumed this was all that was required.

Have I just missed out some important step or is this an actual issue?

**Comment by caio** [comment]
I can confirm this. The odd thing is that accessing /admin/ right after starting the devserver doesn't trigger this error -- This used to happen a lot to me on my own engine also.

Importing `fix_path` and calling `fix_path.fix_sys_path()` before `import markdown` on `markup.py` solves this problem.

**Comment by alexanderfast** [comment]
I can confirm this issue. I can also confirm Caio's workaround. I pushed that fix to my own clone: http://github.com/mizipzor/bloggart/commit/a63471b2e81618a571cec2f57ad142e983be2ac8

**Comment by Arachnid** [comment]
Fixed.
