### ISSUE TITLE
Blog home page throws 404 error

### ISSUE THREAD

**Issue by honza** [Arachnid/bloggart#36]
The main page of the blog '/' shows a big fat whooops. I checked the settings in config.py and everything seems to be in order. I'm running in the SDK on localhost on Linux. Any tips? Thanks

**Comment by Arachnid** [comment]
You need to log in to the admin console at /admin/ - the first time you do this, it generates the static content and the (initially blank) listing pages including the homepage.

**Comment by hymerman** [comment]
I'm getting the same thing, even after visiting /admin/ (choosing to log in as administrator), and hitting the 'regenerate posts' button. It's still a 404 after creating a post, too. This is testing locally, viewing http://localhost:8080/

**Comment by honza** [comment]
I already have some test posts and they render fine. It's the home and tag pages that don't work. Thanks for any tips

**Comment by hymerman** [comment]
Yep, pages render fine for me if I go straight to them, by clicking the 'go to new post' button after creating a post or just typing the URL, but nothing appears on the home page. Tag pages are also 404s.

**Comment by honza** [comment]
Please?

**Comment by hymerman** [comment]
Ah, interesting. Go to localhost:8080/_ah/admin/tasks?queue=default - there's a message there that says "Tasks will not run automatically. Push the 'Run' button to execute each task.". Pressing 'run' on a bunch of the tasks there sorts the problem out. So I guess this is an AppEngine Launcher problem rather than a problem with bloggart?

**Comment by Arachnid** [comment]
Correct.

**Comment by zlouattara** [comment]
create a test post and run task queue once will fix it....
