### ISSUE TITLE
Admin Redirect Issues in firefox ( not chrome )

### ISSUE THREAD

**Issue by ghost** [Arachnid/bloggart#37]
Ok, so here is as much relevant information as possible since I've only installed bloggart a few minutes ago.

In firefox 3.6 ( linux ) if i goto the /admin/\* page i get redirected to login, after successful login i keep getting redirected BACK to the google login. this does not happen in chrome and works as it should.

**Comment by Arachnid** [comment]
Are you using the same account in each browser? Can you use an extension such as Live HTTP Headers to document what redirects are occurring?

**Comment by ghost** [comment]
yes the same account, and i'll try out that extension here in a few minutes

**Comment by ghost** [comment]
seems i was in a hurry when i submitted this issue, after a restart everything seemed to work ok in all browsers. sorry for the false alarm
