### ISSUE TITLE
hardcoded theme name values used in themes

### ISSUE THREAD

**Issue by ghost** [Arachnid/bloggart#39]
I'm not sure how to give you a patch but here is a link to the commit i made for just this change

basicly /default/ becomes /{{config.theme}}/ and /simple/ becomes /{{config.theme}}/ so if a user ( or dev ) changes the name of the theme directory it does not break the appear of the theme

http://github.com/hickups/bloggart/commit/ec1b17be98e681affe159756075e762e64be8c89

**Comment by Arachnid** [comment]
Fixed by hickups.
