### ISSUE TITLE
Atom feed does not respect admin rights

### ISSUE THREAD

**Issue by namankumar** [Arachnid/bloggart#47]
Atom feed contains draft posts. Obviously, this shouldn't be the case.

I'll look at this when as I find time.

**Comment by Arachnid** [comment]
I'm fairly sure this was fixed in a much earlier revision - my own blog certainly doesn't contain drafts in the RSS feed.

**Comment by namankumar** [comment]
You're right, I updated my code and its fine now. Thanks.
