### ISSUE TITLE
<type 'exceptions.ImportError'>: No module named aetycoon

### ISSUE THREAD

**Issue by rogcg** [Arachnid/bloggart#56]
I just download the app and set it up, but  when I launch it and run, it says:

> < type 'exceptions.ImportError' > : No module named aetycoon

there is a `lib/aetycoon/__init__.py` file, it looks like it's ok, but it crashes when I try to run.

the error happens on `static.py` line 14, right where I `import aetycoon`.

what could it be?

**Comment by hymerman** [comment]
Probably submodules aren't present; try:

```
git submodule init
git submodule update
```

Also I'd recommend taking rctay or detro's fork of bloggart; Arachnid's hasn't been updated in a long time.
